# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# 网站标题
title: YUANYUAN-BLOG
# 网站副标题
subtitle: "袁园的博客"
# 网站描述
description: "日常分享"
# 网站关键字
keywords:
# my name
author: xxx
# 使用的语言 ： zh-Hans zh-CN
language: zh-CN
# 网站时区
timezone: ""

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'

# 网址 http:// or https://
url: http://example.com
# 网站根目录
root: /
# 文章的永久链接格式 ：https://hexo.io/zh-cn/docs/permalinks

permalink: :title/
# 永久链接中各部分的默认值
permalink_defaults:

pretty_urls:
  # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
# 资源文件夹 存放内容
source_dir: source
# 公共文件夹 存放生成的站点文件
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories

code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
# 新文件的文件名称
new_post_name: :title.md # File name of new posts
# 预设布局
default_layout: post
# 将标题转换为 title case
titlecase: false # Transform title into titlecase
# 在新标签中打开链接
external_link:
  # 在新标签中打开链接
  enable: true # Open external links in new tab
  # 对整个网站（site）生效或仅对文章（post）生效
  field: site # Apply to the whole site
  # 需要排除的域名。主域名和子域名如 www 需分别配置
  exclude: ""
# 把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0
# 显示草稿
render_drafts: false
# 启动 Asset 文件夹
post_asset_folder: false
# 把链接改为与根目录的相对位址
relative_link: false
# 显示未来的文章
future: true
# 代码块的设置, see Highlight.js section for usage guide
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
# 代码块的设置, see PrismJS section for usage guide
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
# 每页显示的文章量 (0 = 关闭分页功能)
per_page: 10
# 分页目录
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# 当前主题名称。值为false时禁用主题   landscape/默认  maupassant
theme: maupassant

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:yybeaut/yybeaut.github.io.git
  branch: master
